import logging
import os
from datetime import datetime
from typing import List, Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, Security
from fastapi.security import APIKeyHeader
from pydantic import BaseModel, HttpUrl, field_validator
from sqlalchemy.orm import Session

from app.db.database import get_db
from app.db.models import Source, Story

router = APIRouter(tags=["Stories"])
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# API key authentication
# ---------------------------------------------------------------------------

_API_KEY_HEADER = APIKeyHeader(name="X-API-Key", auto_error=False)


def _require_api_key(api_key: Optional[str] = Security(_API_KEY_HEADER)) -> None:
    """Validate the X-API-Key header against the SARANSH_INGEST_API_KEY env var."""
    expected = os.environ.get("SARANSH_INGEST_API_KEY")
    if not expected or not api_key or api_key != expected:
        raise HTTPException(status_code=401, detail="Invalid or missing API key")


# ---------------------------------------------------------------------------
# Request schemas
# ---------------------------------------------------------------------------

class SourceIn(BaseModel):
    outlet: str
    url: HttpUrl
    source_type: Optional[str] = None


class StoryIn(BaseModel):
    title_en: str
    title_hi: str
    summary_en: str
    summary_hi: str
    category: str
    state: Optional[str] = None
    district: Optional[str] = None
    sources: List[SourceIn]

    @field_validator("title_en", "title_hi", "summary_en", "summary_hi", "category")
    @classmethod
    def not_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("field must not be blank")
        return v

    @field_validator("sources")
    @classmethod
    def sources_not_empty(cls, v: List[SourceIn]) -> List[SourceIn]:
        if not v:
            raise ValueError("at least one source is required")
        return v


# ---------------------------------------------------------------------------
# Response schemas
# ---------------------------------------------------------------------------

class SourceOut(BaseModel):
    id: UUID
    outlet: str
    url: str
    source_type: Optional[str]

    model_config = {"from_attributes": True}


class StoryOut(BaseModel):
    id: UUID
    title_en: str
    title_hi: str
    summary_en: str
    summary_hi: str
    category: str
    state: Optional[str]
    district: Optional[str]
    status: str
    sources: List[SourceOut]
    created_at: datetime

    model_config = {"from_attributes": True}


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/stories", response_model=List[StoryOut])
def list_stories(
    limit: int = Query(20, ge=1, le=100),
    offset: int = Query(0, ge=0),
    category: Optional[str] = Query(None),
    state: Optional[str] = Query(None),
    district: Optional[str] = Query(None),
    status: Optional[str] = Query(None),
    db: Session = Depends(get_db),
):
    """Return stories newest-first with optional filtering and pagination."""
    query = db.query(Story)
    if category is not None:
        query = query.filter(Story.category == category)
    if state is not None:
        query = query.filter(Story.state == state)
    if district is not None:
        query = query.filter(Story.district == district)
    if status is not None:
        query = query.filter(Story.status == status)
    return query.order_by(Story.created_at.desc()).offset(offset).limit(limit).all()


@router.get("/stories/{story_id}", response_model=StoryOut)
def get_story(story_id: UUID, db: Session = Depends(get_db)):
    """Return a single story by ID, or 404 if not found."""
    story = db.query(Story).filter(Story.id == story_id).first()
    if story is None:
        raise HTTPException(status_code=404, detail="Story not found")
    return story


@router.post("/stories", response_model=StoryOut, status_code=201, dependencies=[Depends(_require_api_key)])
def ingest_story(payload: StoryIn, db: Session = Depends(get_db)):
    """Ingest a structured story generated by an AI agent. Requires X-API-Key."""
    try:
        story = Story(
            title_en=payload.title_en,
            title_hi=payload.title_hi,
            summary_en=payload.summary_en,
            summary_hi=payload.summary_hi,
            category=payload.category,
            state=payload.state,
            district=payload.district,
            status="draft",
        )
        db.add(story)
        db.flush()  # obtain story.id before inserting sources

        for source_in in payload.sources:
            source = Source(
                story_id=story.id,
                outlet=source_in.outlet,
                url=str(source_in.url),
                source_type=source_in.source_type,
            )
            db.add(source)

        db.commit()
        db.refresh(story)
        logger.info("Ingested story id=%s title='%s'", story.id, story.title_en)
        return story
    except Exception as exc:
        db.rollback()
        logger.exception("Failed to ingest story: %s", exc)
        raise HTTPException(status_code=500, detail="Failed to save story") from exc
