from typing import List, Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from app.api.dependencies import require_api_key
from app.db.database import get_db
from app.db.repositories import stories as stories_repo
from app.schemas.stories import StoryIn, StoryOut
from app.utils import get_logger

router = APIRouter(tags=["Stories"])
logger = get_logger(__name__)


@router.get("/stories", response_model=List[StoryOut])
def list_stories(
    limit: int = Query(20, ge=1, le=100),
    offset: int = Query(0, ge=0),
    category: Optional[str] = Query(None),
    state: Optional[str] = Query(None),
    district: Optional[str] = Query(None),
    status: Optional[str] = Query(None),
    db: Session = Depends(get_db),
):
    """Return stories newest-first with optional filtering and pagination."""
    return stories_repo.list_stories(
        db,
        limit=limit,
        offset=offset,
        category=category,
        state=state,
        district=district,
        status=status,
    )


@router.get("/stories/{story_id}", response_model=StoryOut)
def get_story(story_id: UUID, db: Session = Depends(get_db)):
    """Return a single story by ID, or 404 if not found."""
    story = stories_repo.get_story(db, story_id)
    if story is None:
        raise HTTPException(status_code=404, detail="Story not found")
    return story


@router.post(
    "/stories",
    response_model=StoryOut,
    status_code=201,
    dependencies=[Depends(require_api_key)],
)
def ingest_story(payload: StoryIn, db: Session = Depends(get_db)):
    """Ingest a structured story generated by an AI agent. Requires X-API-Key."""
    try:
        story = stories_repo.create_story(db, payload)
    except Exception as exc:
        logger.exception("story.ingest_failed", category=payload.category)
        raise HTTPException(status_code=500, detail="Failed to save story") from exc

    logger.info("story.ingested", story_id=str(story.id), title=story.title_en)
    return story
