import logging
from datetime import datetime
from typing import List, Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, HttpUrl, field_validator
from sqlalchemy.orm import Session

from app.db.database import get_db
from app.db.models import Source, Story

router = APIRouter(tags=["Stories"])
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Request schemas
# ---------------------------------------------------------------------------

class SourceIn(BaseModel):
    outlet: str
    url: HttpUrl
    source_type: Optional[str] = None


class StoryIn(BaseModel):
    title_en: str
    title_hi: str
    summary_en: str
    summary_hi: str
    category: str
    state: Optional[str] = None
    district: Optional[str] = None
    sources: List[SourceIn]

    @field_validator("title_en", "title_hi", "summary_en", "summary_hi", "category")
    @classmethod
    def not_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("field must not be blank")
        return v

    @field_validator("sources")
    @classmethod
    def sources_not_empty(cls, v: List[SourceIn]) -> List[SourceIn]:
        if not v:
            raise ValueError("at least one source is required")
        return v


# ---------------------------------------------------------------------------
# Response schemas
# ---------------------------------------------------------------------------

class SourceOut(BaseModel):
    id: UUID
    outlet: str
    url: str
    source_type: Optional[str]

    model_config = {"from_attributes": True}


class StoryOut(BaseModel):
    id: UUID
    title_en: str
    title_hi: str
    summary_en: str
    summary_hi: str
    category: str
    state: Optional[str]
    district: Optional[str]
    status: str
    sources: List[SourceOut]
    created_at: datetime

    model_config = {"from_attributes": True}


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------

@router.post("/stories", response_model=StoryOut, status_code=201)
def ingest_story(payload: StoryIn, db: Session = Depends(get_db)):
    """Ingest a structured story generated by an AI agent."""
    try:
        story = Story(
            title_en=payload.title_en,
            title_hi=payload.title_hi,
            summary_en=payload.summary_en,
            summary_hi=payload.summary_hi,
            category=payload.category,
            state=payload.state,
            district=payload.district,
            status="draft",
        )
        db.add(story)
        db.flush()  # obtain story.id before inserting sources

        for source_in in payload.sources:
            source = Source(
                story_id=story.id,
                outlet=source_in.outlet,
                url=str(source_in.url),
                source_type=source_in.source_type,
            )
            db.add(source)

        db.commit()
        db.refresh(story)
        logger.info("Ingested story id=%s title='%s'", story.id, story.title_en)
        return story
    except Exception as exc:
        db.rollback()
        logger.exception("Failed to ingest story: %s", exc)
        raise HTTPException(status_code=500, detail="Failed to save story") from exc
